package utility;

import javafx.scene.Node;
import javafx.scene.input.RotateEvent;
import javafx.scene.input.ScrollEvent;
import javafx.scene.input.TouchEvent;
import javafx.scene.input.ZoomEvent;
import javafx.scene.layout.Pane;
import javafx.stage.Window;

/**
 * Wrapper class for a Pane object to enable base touch functionality, including zooming, rotating and scrolling
 */
public class TouchPaneController {

    /**
     * Pane to perform touch operations on
     */
    private Pane pane;

    /**
     * Creates a new TouchPaneController
     * @param pane base pane
     */
    public TouchPaneController(Pane pane) {
        this.pane = pane;
    }

    /**
     * Zooms in and out of the pane by the zoom event generated by the user
     * @param zoomEvent zoom event
     */
    public void zoomPane(ZoomEvent zoomEvent) {
        Window currentWindow = ((Node)zoomEvent.getTarget()).getScene().getWindow();
        pane.setScaleX(pane.getScaleX() * zoomEvent.getZoomFactor());
        currentWindow.setWidth(currentWindow.getWidth() * zoomEvent.getZoomFactor());
        pane.setScaleY(pane.getScaleY() * zoomEvent.getZoomFactor());
        currentWindow.setHeight(currentWindow.getHeight() * zoomEvent.getZoomFactor());
        resizePane();
    }

    /**
     * Rotates the pane using the rotate event generated by the user
     * @param rotateEvent rotate event
     */
    public void rotatePane(RotateEvent rotateEvent) {
        pane.setRotate(pane.getRotate() + rotateEvent.getAngle() * 0.8);
    }

    /**
     * Scrolls in four directions along pane by a scroll event generated by the user
     * @param scrollEvent scroll event
     */
    public void scrollPane(ScrollEvent scrollEvent) {
        if(!scrollEvent.isInertia()) {
            pane.setTranslateX(pane.getTranslateX() + scrollEvent.getDeltaX());
            pane.setTranslateY(pane.getTranslateY() + scrollEvent.getDeltaY());
        }
    }

    private void resizePane() {
        Window currentWindow = pane.getScene().getWindow();
        double stageWidth = currentWindow.getWidth();
        double stageHeight = currentWindow.getHeight();
        pane.resize(stageWidth, stageHeight);
        pane.setTranslateX(0);
        pane.setTranslateY(0);
    }

}
